// Third-party licence collector (THIRD_PARTY_NOTICES.md §3): generates the
// per-release dependency licence manifest straight from package-lock.json and
// the installed packages. Run at every release:
//
//   npm run licenses
//
// Output: THIRD_PARTY_LICENSES.md at the repo root — for every direct and
// transitive dependency actually shipped (and dev-only tooling, classified as
// such): package name, exact resolved version, SPDX licence identifier,
// copyright notice, source repository link, and (for shipped packages) the full
// licence text. The app serves this file from Settings → Legal (§3.4: the
// notices must be accessible to users from within the application).
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(fileURLToPath(new URL("..", import.meta.url)));
const lock = JSON.parse(
  readFileSync(join(repoRoot, "package-lock.json"), "utf8"),
);

// The app version this manifest corresponds to (single source: server config).
const configSource = readFileSync(
  join(repoRoot, "apps", "server", "src", "config.ts"),
  "utf8",
);
const appVersion =
  /version:\s*"([^"]+)"/.exec(configSource)?.[1] ?? "unknown";

// ---------------------------------------------------------------------------

function findLicenceFile(dir) {
  let entries;
  try {
    entries = readdirSync(dir);
  } catch {
    return null;
  }
  const hit = entries.find((name) =>
    /^(licen[cs]e|copying|notice)(\.|-|$)/i.test(name),
  );
  return hit ? join(dir, hit) : null;
}

function extractCopyright(licenceText, fallback) {
  if (licenceText) {
    const lines = licenceText
      .split(/\r?\n/)
      .filter((line) => /copyright/i.test(line) && line.trim().length < 200)
      .slice(0, 3)
      .map((line) => line.trim());
    if (lines.length > 0) return lines.join(" / ");
  }
  return fallback ?? "(no explicit copyright notice in package)";
}

function repositoryUrl(pkg) {
  const repo = pkg.repository;
  const raw = typeof repo === "string" ? repo : repo?.url;
  if (!raw) return pkg.homepage ?? "";
  return raw
    .replace(/^git\+/, "")
    .replace(/^git:\/\//, "https://")
    .replace(/^ssh:\/\/git@/, "https://")
    .replace(/\.git$/, "");
}

// ---------------------------------------------------------------------------

// lockfile v3: `packages` maps install paths to entries. Keep real node_modules
// packages only (workspace folders and the root have no "node_modules/" in the
// key); dedupe by name@version (nested copies repeat).
const seen = new Map();
for (const [path, entry] of Object.entries(lock.packages ?? {})) {
  const at = path.lastIndexOf("node_modules/");
  if (at === -1 || entry.link) continue;
  const name = path.slice(at + "node_modules/".length);
  if (!entry.version) continue;
  const key = `${name}@${entry.version}`;
  const prior = seen.get(key);
  // A package is SHIPPED unless every occurrence is dev-only.
  const dev = entry.dev === true;
  if (prior) {
    prior.dev = prior.dev && dev;
    continue;
  }

  const dir = join(repoRoot, path);
  let pkg = {};
  try {
    pkg = JSON.parse(readFileSync(join(dir, "package.json"), "utf8"));
  } catch {
    // Absent on disk (e.g. optional platform package): record from lock only.
  }
  const licenceFile = findLicenceFile(dir);
  const licenceText = licenceFile ? readFileSync(licenceFile, "utf8") : null;
  const author =
    typeof pkg.author === "string" ? pkg.author : pkg.author?.name;

  seen.set(key, {
    name,
    version: entry.version,
    dev,
    spdx: pkg.license ?? entry.license ?? "(not declared)",
    copyright: extractCopyright(licenceText, author),
    repository: repositoryUrl(pkg),
    licenceText,
  });
}

const all = [...seen.values()].sort((a, b) =>
  a.name === b.name
    ? a.version.localeCompare(b.version)
    : a.name.localeCompare(b.name),
);
const shipped = all.filter((entry) => !entry.dev);
const devOnly = all.filter((entry) => entry.dev);

// ---------------------------------------------------------------------------

function table(entries) {
  const rows = entries.map(
    (entry) =>
      `| ${entry.name} | ${entry.version} | ${entry.spdx} | ${
        entry.repository || "—"
      } |`,
  );
  return [
    "| Package | Version | Licence (SPDX) | Repository |",
    "|---|---|---|---|",
    ...rows,
  ].join("\n");
}

const parts = [];
parts.push(`# Vaenyx — Third-Party Licences (Release Manifest)

> Machine-generated by \`scripts/licenses.mjs\` (THIRD_PARTY_NOTICES.md §3) —
> do not edit by hand; regenerate at every release.

- **App version:** ${appVersion}
- **Shipped third-party packages (direct + transitive):** ${shipped.length}
- **Development-only tooling (not distributed with the app):** ${devOnly.length}

## 1. Shipped packages

These packages (or code built from them) are distributed with Vaenyx. Each is
listed with its licence, copyright notice and source; full licence texts follow
in Section 3.

${table(shipped)}

## 2. Development-only tooling

Used to build and test Vaenyx; not distributed with the application.

${table(devOnly)}

## 3. Licence texts and copyright notices (shipped packages)
`);

for (const entry of shipped) {
  parts.push(`### ${entry.name}@${entry.version}

- **Licence:** ${entry.spdx}
- **Copyright:** ${entry.copyright}
- **Source:** ${entry.repository || "—"}
`);
  if (entry.licenceText) {
    parts.push("```text\n" + entry.licenceText.trim() + "\n```\n");
  } else {
    parts.push(
      "_No licence file shipped inside the package; see the SPDX identifier above and the package repository._\n",
    );
  }
}

const outPath = join(repoRoot, "THIRD_PARTY_LICENSES.md");
writeFileSync(outPath, parts.join("\n"), "utf8");
console.log(
  `THIRD_PARTY_LICENSES.md written: ${shipped.length} shipped + ${devOnly.length} dev-only packages (app ${appVersion})`,
);

// Sanity guard: a manifest with implausibly few shipped packages means the
// lockfile walk broke — fail loudly rather than shipping an empty manifest.
if (shipped.length < 5) {
  console.error("ERROR: implausibly few shipped packages — check the walker.");
  process.exit(1);
}
